### ISSUE TITLE
[Bug] Bungee did not alert and ban

### ISSUE THREAD

**Issue by BingYanchi** [Elikill58/Negativity#325]
### Which platform are you using ?

Bungeecord

### Versions of Negativity and of the server

My version is: 2.4.2

### Step to reproduce

Bungee config.yml:
```yaml
Database:
  isActive: true
  # To get the information. We use the player uuid to get the information.
  # We get only what you write. We never add or remove something.
  # We don't save your private information about your database
  url: "mysql.yistars.net/negativity"
  user: Negativity
  password: "password"

# Configuration of the permissions subsystem. For more information
# see https://github.com/Elikill58/Negativity/wiki/Permissions
Permissions:
  # The checker indicates if a player has a specific permission.
  # By default only 'platform' is available
  checker: platform
  showAlert:
    default: "negativity.alert"
  admin:
    default: "negativity.admin"
  showReport:
    default: "negativity.seereport"
  # To bypass ban system
  notBanned:
    default: "negativity.notbanned"

Translation:
  active: true # enable or disable the translation
  lang_available:
  - ar_EG
  - cs_CZ
  - de_DE
  - en_GB
  - en_US
  - es_ES
  - fr_FR
  - hu_HU
  - it_IT
  - id_ID
  - ko_KR
  - nl_NL
  - no_NO
  - pl_PL
  - pt_BR
  - ro_RO
  - ru_RU
  - sq_SQ
  - sv_SV
  - th_TH
  - vi_VN
  - zh_CN
  default: zh_CN
  # The provider used to get translated messages, useful if you want to customize the way Negativity gets its messages.
  # The only one available out-of-the-box is "platform".
  provider: platform

# Configuration of the bans subsystem. For more information
# see https://github.com/Elikill58/Negativity/wiki/Bans
ban:
  active: true
  # Processors manage bans. Only one processor can be used at the time.
  # Available processors :
  # - file : Saves bans under the ban/ directory of the configuration directory
  # - database : Saves bans in a database. Needs a configured database (see the Database category)
  # - command : Runs commands to ban or unban
  # The following plugins are also supported :
  # - advancedban
  # - dkbans
  # - litebans
  # - professionalbans
  # Defaults to "file"
  processor: "database"
  # Commands to execute when using the "command" processor
  # You can execute as many commands as you want. Order is respected.
  #
  # Available placeholders:
  # %uuid% : uuid of banned player
  # %name% : name of banned player
  # %ip% : ip of the banned player
  # %reason% : detected cheat
  # %alert% : number of alerts for the detected cheat that triggered the ban
  # %all_alert% : all alerts for the detected cheat since you added Negativity on your server
  command:
    ban:
    - "ban %uuid% %reason%"
    unban:
    - "unwarn %uuid% %reason%"
  # Need to be banned
  reliability_need: 95
  alert_need: 10
  # How to calculate the time during the player will be banned
  # IN MILLISECONDES
  time:
    # %reliability% : reliability of last alert
    # %alert% : number of alert sent
    calculator: "360000000 + (%reliability% * 20 * %alert%)"
  def:
    # Number that you need to be ban definitly
    ban_time: 2
  file:
    # Log expired or revoked bans when using the "file" processor
    log_bans: true
  database:
    # Log expired or revoked bans when using the "database" processor
    log_bans: true

# Accounts hold player-specific data of the plugin, like their language and alerts count.
accounts:
  storage:
    id: "database"
```

Spigot Config.yml:
```yaml
log_alerts: true
log_alerts_in_console: true
tps_alert_stop: 19 # if you get less TPS then this value, all alert will be disabled
# Don't send ping message to proxy, just let say there is Negativity on proxy
use-proxy-force: false

commands:
  # Options to enable or disable commands
  # Manage /nreport (Alias: /report)
  report: true
  # Manage Mod command :
  # Manage /nkick (Alias: /kick)
  kick: true
  # Manage /nmod (Alias: /mod)
  mod: true
  # Manage /nlang (Alias: /lang)
  lang: true
  # Manage all commands about chat
  chat:
    # Enable the /clearchat command
    clear: true
    # Enable the /lockchat command
    lock: true

# The time between 2 /report
# in milliseconds
# -1 to disable
time_between_report: 1000

Database:
  isActive: true
  # To get the information. We use the player uuid to get the information.
  # We get only what you write. We never add or remove something.
  # We don't save your private information about your database
  url: "mysql.yistars.net/negativity"
  user: Negativity
  password: "YXDCydt24n4ABx8J"
  type: "mysql"

inventory:
  alerts:
    no_started_verif_cheat: false # Don't see if the player isn't analyse for this cheat
    only_cheat_active: true # The cheat with an active detection
  inv_freeze_active: true

# Bypass when you add effects
#
items: 
  #ITEM_NAME:
  # when: WHEN_DISABLE_DETECTION
  # cheats: CHEATS_DETECTION_DISABLED (it's the ID of the cheats like fly, speed)
  #
  # when available:
  # always : disable when the player get it in their hand
  # right_click : disable when the player right click
  # left_click : disable when the player left click
  # looking : disable when the player is looking a specific type
  # below : disable according to the block below the player
  #
  BEDROCK:
    when: always
    cheats: speed,fly

# Configuration of the permissions subsystem. For more information
# see https://github.com/Elikill58/Negativity/wiki/Permissions
Permissions:
  # The checker indicates if a player has a specific permission.
  # By default only 'platform' is available
  checker: platform
  check:
    default: "negativity.check"
  showAlert:
    default: "negativity.alert"
  showReport:
    default: "negativity.seereport"
  verif:
    default: "negativity.verif"
  manageCheat:
    default: "negativity.managecheat"
  reload:
    default: "negativity.reload"
  report_wait:
    default: "negativity.reportwait"
  report:
    default: "negativity.report"
  ban:
    default: "negativity.ban"
  unban:
    default: "negativity.unban"
  mod:
    default: "negativity.mod"
  lang:
    default: "negativity.lang"
  chat:
    clear:
      default: "negativity.chat.cleat"
    lock:
      default: "negativity.chat.lock"
    lock_bypass:
      default: "negativity.chat.lock_bypass"
  bypass:
    active: true
    ban:
      # Bypass ban (auto and /nban)
      default: "negativity.bypass.ban"
    all:
      default: "negativity.bypass.all"
    forcefield:
      default: "negativity.bypass.forcefield"
    fastplace:
      default: "negativity.bypass.fastplace"
    speed:
      default: "negativity.bypass.speed"
    autoclick:
      default: "negativity.bypass.autoclick"
    fly:
      default: "negativity.bypass.fly"
    antipotion:
      default: "negativity.bypass.antipotion"
    fasteat:
      default: "negativity.bypass.fasteat"
    regen:
      default: "negativity.bypass.regen"
    antiknockback:
      default: "negativity.bypass.antiknockback"
    jesus:
      default: "negativity.bypass.jesus"
    nofall:
      default: "negativity.bypass.nofall"
    blink:
      default: "negativity.bypass.blink"
    spider:
      default: "negativity.bypass.spider"
    fastbow:
      default: "negativity.bypass.fastbow"
    scaffold:
      default: "negativity.bypass.scaffold"
    step:
      default: "negativity.bypass.step"
    noslowdown:
      default: "negativity.bypass.noslowdown"
    fastladder:
      default: "negativity.bypass.fastladder"
    phase:
      default: "negativity.bypass.phase"
    autosteal:
      default: "negativity.bypass.autosteal"
    nuker:
      default: "negativity.bypass.nuker"
    airjump:
      default: "negativity.bypass.airjump"
    chat:
      default: "negativity.bypass.chat"
    noweb:
      default: "negativity.bypass.noweb"
    critical:
      default: "negativity.bypass.critical"
    inventorymove:
      default: "negativity.bypass.inventorymove"
    faststairs:
      default: "negativity.bypass.faststairs"
    nopitchlimit:
      default: "negativity.bypass.nopitchlimit"
    timer:
      default: "negativity.bypass.timer"

Translation:
  active: true # enable or disable the translation
  lang_available:
  - ar_EG
  - cs_CZ
  - de_DE
  - en_GB
  - en_US
  - es_ES
  - fr_FR
  - hu_HU
  - it_IT
  - id_ID
  - ko_KR
  - nl_NL
  - no_NO
  - pl_PL
  - pt_BR
  - ro_RO
  - ru_RU
  - sq_SQ
  - sv_SV
  - th_TH
  - vi_VN
  - zh_CN
  default: zh_CN
  # The provider used to get translated messages, useful if you want to customize the way Negativity gets its messages.
  # The only one available out-of-the-box is "platform".
  provider: platform

report:
  spam:
    # Name of report (which is also used as reason)
    name: "&6垃圾信息/广告"
    # the material in inventory
    material: YELLOW_BANNER
    # the slot of item in inventory
    slot: 0
    # the message sent to player when report player
    message: "&6%name% &a因 %reason% &a而被举报"
    # "permission" is not necessary. If you don't set it, everyone will be able to use it.
  insult:
    name: "&c侮辱"
    material: RED_BANNER
    slot: 1
    message: "&6%name% &a因 %reason% &a而被举报"
    permission: "negativity.report.insult"
  #racism:
  #  name: "&c种族歧视"
  #  material: RED_BANNER
  #  slot: 2
  #  message: "&6%name% &a因 %reason% &a而被举报"
  #  permission: "negativity.report.racism"
  #high_ping:
  #  name: "&4High ping"
  #  material: BLACK_BANNER
  #  slot: 9
  #  message: "&6%name% &a因 %reason% &a而被举报"
  #  permission: "negativity.report.ping"
  wrong_name:
    name: "&4不合适的昵称"
    material: BLACK_BANNER
    slot: 2
    message: "&6%name% &a因 %reason% &a而被举报"
    permission: "negativity.report.name"
  cheat:
    name: "&4作弊"
    material: BLACK_BANNER
    slot: 3
    message: "&6%name% &a因 %reason% &a而被举报"
    permission: "negativity.report.cheat"


kicks:
  spam:
    # Name of report (which is also used as reason)
    name: "&6垃圾信息/广告"
    # the material in inventory
    material: YELLOW_BANNER
    # the slot of item in inventory
    slot: 0
    # the message sent to player which use the inventory
    message: "&6%name% &a因 %reason% &a而被踢出"
    # the command to run when mod click on the item
    command: "nkick %name% 垃圾信息/广告"
    # "permission" is not necessary. If you don't set it, everyone will be able to use it.
  insult:
    name: "&c侮辱"
    material: ORANGE_BANNER
    slot: 1
    message: "&6%name% &a因 %reason% &a而被踢出"
    command: "nkick %name% 侮辱"
    permission: "negativity.report.insult"
  invalid_name:
    name: "&c不合适的昵称"
    material: RED_BANNER
    slot: 2
    message: "&6%name% &a因 %reason% &a而被踢出"
    command: "nkick %name% 不合适的昵称"
    permission: "negativity.report.insult"

alert:
  show:
    # Available types :
    # instant: instantly send alerts
    # time: the value (in milliseconds) corresponds to the time between 2 alerts. Use '-1' to send messages instantly
    # amount: the value is the amount of required alerts of one cheat to send the message.
    type: "amount"
    # The value according to the type.
    value: 5
  
  # To run command when someone get alert
  command:
    active: false
    # Cooldown in milliseconds between 2 call of commands (time for each player)
    cooldown: 0
    # Reliability need to run command
    reliability_need: 80
    # Available arguments:
    # %name% : Name of player who cheat
    # %uuid% : UUID of player who cheat
    # %report_type% : Type of detected cheat (Know if Negativity consider it as Warning or Violation)
    # %cheat_key% : Cheat key (like "nofall") : You cannot edit it
    # %cheat_name% : Cheat name (like "NoFall") : You can edit it just below
    # %reliability% : Reliability of the alert
    run:
    - "mycommand %name% %cheat_key% %reliability%"


# Accounts hold player-specific data of the plugin, like their language and alerts count.
accounts:
  storage:
    # The ID of the storage to use.
    #
    # The following are available out-of-the-box:
    # - file : stored in files under ./plugins/Negativity/user/
    # - database : uses a database
    # Defaults to "file"
    id: "database"

# A verification is used to monitor a player's activity.
verif:
  # The default duration of a verification, in ticks (20 ticks = 1 second)
  time: 200
  # If true, mutes alerts a player generates when it is being verified
  # Alerts for a specific cheat can be forcibly muted by setting cheats.<cheat>.check_in_verif to false
  disable_alert_on_verif: true

  storage:
    # The ID of the storage to use.
    #
    # The following are available out-of-the-box:
    # - file : stored in files under ./plugins/Negativity/verif/
    # - database : uses a database
    # Defaults to "file"
    id: "database"

region-bypass:
  enabled: false
  1:
    # You need WorldGuard for the region
    regions:
    - "spawn"
    # Default worlds names (or Multiverse names)
    worlds:
    - "world_the_end"
    # the cheats keys
    cheats:
    - "fly"
# Manage webhook
webhooks:
  enable: false
  hook:
    discord-example:
      type: "discord"
      # register the webhook URL used by Negativity
      url: "https://discord.com/api/webhooks/theRestOfDiscordUrl"
      # Configure messages presentation
      # If you don't set one of them, it will get the default configuration
      #
      # Placeholders available everywhere :
      # %name% : Name of the player which procude the message
      # %uuid% : UUID of the player which procude the message
      # %ip% : IP of the player which produce the message
      # %date% : Date when the player procude the message
      # %sender% : The sender of the message (such as banner or reporter)
      # %ping% : The ping of the player
      # %world% : The world of the player
      # %server_name% : The name of the server where the player is
      # %server_version% : Version of the server
      # %player_version% : Version of the player
      # %tps% : Actual server TPS
      # 
      messages:
        # Configure discord webhook message for ban.
        #
        # Placeholders available :
        # %cheat% : the cheat name
        # %amount% : Amount of alert made by player
        # %reliability% : Reliability of the cheat
        alert:
          enabled: true
          # The name which will send the message
          username: "Negativity Alert"
          # The content of the message
          content: ""
          # The URL of the message avatar
          avatar_url: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
          # Now let's configure embed message (the section with black background)
          embed:
            # Color of the embed (used with the line on the left)
            # More informations: https://docs.oracle.com/javase/7/docs/api/java/awt/Color.html
            color: "65280"
            # The embed title
            title: "Negativity Alert"
            # Main description
            description: "%name% seems to use %cheat% %amount%x (Reliability: %reliability%%)"
            # All fields.
            # There is 3 fields per line MAX.
            # Else, they will automatically be on the next line.
            fields:
              1:
                # The key which will be at top of field (and bold)
                key: "Player Name"
                # The value of the field
                value: "%name%"
                # If the field is inline
                inline: true
              2:
                key: "Ping"
                value: "%ping% ms"
                inline: true
              3:
                key: "Version"
                value: "%player_version%"
                inline: true
              4:
                key: "World"
                value: "%world%"
                inline: true
              5:
                key: "Server Name"
                value: "%server_name%"
                inline: true
              6:
                key: "Server TPS"
                value: "%tps%"
                inline: true
              7:
                key: "Player UUID"
                value: "%uuid%"
                inline: false
            # Thumbnail of the message
            thumbnail: ""
            # The footer of the message
            footer:
              name: "Negativity - %date%"
              link: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
            # Author details of the message
            author:
              name: ""
              link: "https://github.com/Elikill58/Negativity"
              icon: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
        # Configure discord webhook message for ban.
        #
        # Placeholders available :
        # %name% : Name of the banned player
        # %uuid% : UUID of the banned player
        # %date% : Date when the player have been banned
        # %reason% : Reason of the ban
        ban:
          enabled: true
          # The name which will send the message
          username: "Negativity"
          # The content of the message
          content: ""
          # The URL of the message avatar
          avatar_url: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
          # Now let's configure embed message (the section with black background)
          embed:
            # Color of the embed (used with the line on the left)
            color: "red"
            # The embed title
            title: "Ban"
            # Main description
            description: "%name% have been banned by %sender% for %reason%"
            # All fields.
            # There is 3 fields per line MAX.
            # Else, they will automatically be on the next line.
            fields:
              1:
                # The key which will be at top of field (and bold)
                key: "Player name"
                # The value of the field
                value: "%name%"
                # If the field is inline
                inline: true
              2:
                key: "Player UUID"
                value: "%uuid%"
                inline: true
            # Thumbnail of the message
            thumbnail: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
            # The footer of the message
            footer:
              name: "Negativity - %date%"
              link: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
            # Author details of the message
            author:
              name: "Negativity"
              link: "https://github.com/Elikill58/Negativity"
              icon: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
        # Configure discord webhook message for ban.
        #
        # Placeholders available :
        # %reason% : Name of the banned player
        kick:
          enabled: true
          # The name which will send the message
          username: "Negativity"
          # The content of the message
          content: ""
          # The URL of the message avatar
          avatar_url: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
          # Now let's configure embed message (the section with black background)
          embed:
            # Color of the embed (used with the line on the left)
            color: "blue"
            # The embed title
            title: "Kick"
            # Main description
            description: "%name% have been kicked by %sender% for %reason%"
            # All fields.
            # There is 3 fields per line MAX.
            # Else, they will automatically be on the next line.
            fields:
              1:
                # The key which will be at top of field (and bold)
                key: "Player name"
                # The value of the field
                value: "%name%"
                # If the field is inline
                inline: true
              2:
                key: "Player UUID"
                value: "%uuid%"
                inline: true
            # Thumbnail of the message
            thumbnail: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
            # The footer of the message
            footer:
              name: "Negativity - %date%"
              link: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
            # Author details of the message
            author:
              name: "Negativity"
              link: "https://github.com/Elikill58/Negativity"
              icon: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
        # Configure discord webhook message for ban.
        #
        # Placeholders available :
        # %reason% : Name of the banned player
        report:
          enabled: true
          # The name which will send the message
          username: "Negativity"
          # The content of the message
          content: ""
          # The URL of the message avatar
          avatar_url: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
          # Now let's configure embed message (the section with black background)
          embed:
            # Color of the embed (used with the line on the left)
            color: "red"
            # The embed title
            title: "Report"
            # Main description
            description: "%name% have been reported by %sender% for %reason%"
            # All fields.
            # There is 3 fields per line MAX.
            # Else, they will automatically be on the next line.
            fields:
              1:
                # The key which will be at top of field (and bold)
                key: "Player name"
                # The value of the field
                value: "%name%"
                # If the field is inline
                inline: true
              2:
                key: "Player UUID"
                value: "%uuid%"
                inline: true
            # Thumbnail of the message
            thumbnail: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
            # The footer of the message
            footer:
              name: "Negativity - %date%"
              link: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
            # Author details of the message
            author:
              name: "Negativity"
              link: "https://github.com/Elikill58/Negativity"
              icon: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"

    discord-another-example:
      type: "discord"
      url: "https://discord.com/api/webhooks/theRestOfSecondDiscordUrl"
```

Spigot bans.yml:
```yaml
#################################
#                               #
#     Negativity AntiCheat      #
#                               #
#     Configuration of ban      #
#                               #
#################################

# Configuration of the bans subsystem. For more information
# see https://github.com/Elikill58/Negativity/wiki/Bans

# Enable or disable ALL ban feature
active: true

# Manage bans commands
commands:
  # Manage /nban (Alias: /ban)
  # DON'T FORGET TO ENABLE BAN BELOW
  ban: false
  # Manage /nunban (Alias: /unban)
  # DON'T FORGET TO ENABLE BAN BELOW
  unban: false



# Processors manage bans. Only one processor can be used at the time.
# Available processors :
# - file : Saves bans under the ban/ directory of the configuration directory
# - database : Saves bans in a database. Needs a configured database (see the Database category)
# - command : Runs commands to ban or unban
# - bukkit : Uses Bukkit's ban system
# - proxy : Forwards ban execution and revocations to the proxy companion plugin.
#   You must enable bans on the proxy plugin's configuration for it to work
# The following plugins are also supported :
# - maxbans
# - advancedban
# - litebans
# - dkbans
# - professionalbans
# Defaults to "file"
processor: "proxy"
# Commands to execute when using the "command" processor
# You can execute as many commands as you want. Order is respected.
#
# Available placeholders:
# %uuid% : uuid of banned player
# %name% : name of banned player
# %ip% : ip of the banned player
# %reason% : detected cheat
# %alert% : number of alerts for the detected cheat that triggered the ban
# %all_alert% : all alerts for the detected cheat since you added Negativity on your server
command:
  ban:
  - "ban %uuid% %reason%"
  unban:
  - "unban %uuid% %reason%"

# Set auto ban or not
auto: true
# Need to be banned
reliability_need: 95
alert_need: 10
# How to calculate the time during the player will be banned
# IN MILLISECONDES
time:
  # %reliability% : reliability of last alert
  # %alert% : number of alert sent
  calculator: "360000000 + (%reliability% * 20 * %alert%)"
def:
  # Number that you need to be ban definitly
  ban_time: 2
file:
  # Log expired or revoked bans when using the "file" processor
  log_bans: true
database:
  # Log expired or revoked bans when using the "database" processor
  log_bans: true

# Manage alternative account on same IP
# More information on wiki:
# https://github.com/Elikill58/Negativity/wiki/Bans
alt:
  active: false
  # the key tell the X th account.
  # Here, it's for the second account
  2:
    action: alert
    message: "&a[&2Negativity&a]&c &cWarn: you are already ban on another account."
  3:
    action: alert_mod
    message: "&a[&2Negativity&a]&c &cWarn: %name% just logged but he has already 2 banned account on same IP."
  4:
    action: ban
    message: "Alt unauthorized"
    # the time of the ban in milliseconds.
    # set '-1' or "def: true" for definitive ban
    time: 360000
    # condition to be banned
    # Get Warn and Violation from ALL account
    condition:
      # Need at least 30 warn (violations are count as warn)
      warning: 30
      # Need at least 10 violations
      violation: 10
  5:
    action: ban
    message: "Alt unauthorized"
    def: true
    condition:
      warning: 40
      violation: 20
  6:
    # the ban_all action ban definitively all account on the IP
    action: ban_all
  # Such as there is not any information for 6th, 7th ... account, we will take the last, so the 5th.


sanctions:
  ads:
    name: "&1Ads &6(7 days)"
    material: BLUE_BANNER
    slot: 0
    message: "&6%name% &ahave been banned for %reason%"
    command: "nban %name% 7d Ads"
    permission: "negativity.sanction.ads"
    lore:
    - "&7Ban %name% for Ads"
    - "&7During 7 days"
  racism:
    name: "&9Racism &6(7 days)"
    material: BLUE_BANNER
    slot: 1
    message: "&6%name% &ahave been banned for %reason%"
    command: "nban %name% 7d Cheat"
    permission: "negativity.sanction.racism"
    lore:
    - "&7Ban %name% for Racism"
    - "&7During 30 days"
  dirty:
    name: "&8Dirty (Skin or Build) &6(Definitively)"
    material: BROWN_BANNER
    slot: 2
    message: "&6%name% &ahave been banned for %reason%"
    command: "nban %name% def Dirty"
    permission: "negativity.sanction.dirty"
    lore:
    - "&7Ban %name% for dirty skin and/or build"
    - "&7Definitly"
  irl_threat:
    name: "&6IRL threat &6(1 year)"
    material: ORANGE_BANNER
    slot: 9
    message: "&6%name% &ahave been banned for %reason%"
    command: "nban %name% 1y Cheat"
    permission: "negativity.sanction.irl_threat"
    lore:
    - "&7Ban %name% for IRL threat"
    - "&7During 1 year"
  cheat:
    name: "&4Cheat &6(30d)"
    material: RED_BANNER
    slot: 10
    message: "&6%name% &ahave been banned for %reason%"
    command: "nban %name% 30d Cheat"
    permission: "negativity.sanction.cheat"
    lore:
    - "&7Ban %name% for cheat"
    - "&7During 30 days"
  cheat_confession:
    name: "&4Cheat confession &6(2 months)"
    material: RED_BANNER
    slot: 11
    message: "&6%name% &ahave been banned for %reason%"
    command: "nban %name% 2mo Cheat confession"
    permission: "negativity.sanction.cheat_confession"
    lore:
    - "&7Ban %name% for cheat confession"
    - "&7During 2 months"
  hack:
    name: "&4Hack &6(Definitively)"
    material: BLACK_BANNER
    slot: 12
    message: "&6%name% &ahave been banned for %reason%"
    command: "nban %name% def Hack"
    permission: "negativity.sanction.hack"
    lore:
    - "&7Ban %name% for Hack"
    - "&7Definitly"
```
